### ISSUE TITLE
New Galaxy seems to have stalled

### ISSUE THREAD

**Issue by LtanHonor** [Ramblurr/Far-Horizons#4]
I know that this is old code, and might not work on everything.  I have installed the appropriate requirements for Debian on Raspberry Pi and everything did compile correctly according to make.all.  When I go in to issue the command:

python3 ../tools/game_setup.py < players.csv

I get the following outputs:

2 species defined.
Executing NewGalaxy

Nothing else has happened since starting this command 2 hours ago.  I am surmising that there is something amiss with running it from a PI, but not knowing anything about the program...

Has anyone actually run this on a relatively new setup, or is this something that I need to not use a PI for?

Thanks in advance.

**Comment by ravenzachary** [comment]
Hi @LtanHonor I have it running on a Linux server, and a few other people do, as well. We're are in a test game now if you want to join. The test game mailing list is also a good place to connect with the other people who have the code compiled and working. Send me an email to raven at rinzai dot com.

**Comment by Ramblurr** [comment]
@LtanHonor if you want to send me the `players.csv` file I can help troubleshoot it for you.

**Comment by LtanHonor** [comment]
Hey @Ramblurr.  I believe that part of the problem is that I have been trying to get this to work on a Raspberry Pi Zero Wireless.  I have been trying to get an old linux server back in service so that I can work on getting it running there, but... you know.. life.  I need to revisit everything soon though as this is something that I am quite keen on hosting for a few family members and close friends.

**Comment by mdhender** [comment]
@LtanHonor , we've been working on getting this to run on both 32- and 64-bit Linux boxes. Should not be much longer.

**Comment by LtanHonor** [comment]
Thanks for the update @mdhender!  I have finally gotten a stable system running linux x32 to start digging into this again.  I will work on it from here and then help testing it, if needed, on x64 as well.   

Cheers!
