### ISSUE TITLE
Data files are not compatible between 32- and 64- bit systems

### ISSUE THREAD

**Issue by mdhender** [Ramblurr/Far-Horizons#6]
The data files (galaxy.dat, stars.dat, etc) assume the files were created with the current system's word sizes and byte-ordering. This makes it difficult to share data files between systems.

**Comment by mdhender** [comment]
I created a branch (https://github.com/mdhender/Far-Horizons/tree/main) that updates the get and save functions to use the <stdint.h> integer types. That won't help for byte-ordering, but it's a step towards architecture-neutral files.

Unfortunately, this branch also contains all the updates that I've made to fix the compiler warnings and errors on Windows using CMake. I'm still testing/debugging these changes, so it will be some time before they're ready to push.

The get/save code is in the `*io.c` and `*io.h` files, so we could cherry-pick them if needed.

**Comment by mdhender** [comment]
Update: It looks like the core code is complete. I was able to run a complete turn with the engine. I'm working through the GM utilities now. (Those are the programs called in the `tools/game_setup.py` script.)

**Comment by Ramblurr** [comment]
Cool! Thanks for this, it's a welcome addition. Let me know when your branch is ready, or make a PR, and we can merge it into this one.

**Comment by mdhender** [comment]
Will do. It may be a bit tricky since I created a "main" branch for it, not realizing that you'd already done so. I'll work through the merge conflicts and then double check the commits that you and Raven have made since I started down this road.

**Comment by mdhender** [comment]
Update: All the commands (except PrintMap) have been cleaned up. Everything (except for PrintMap) compiles on Linux and Windows using CMake. (The license for the PrintMap command doesn't allow modifications, so I left it as is.) I'm busy testing the round trip for 32- and 64-bit binary to JSON and back. I ***hope*** to create the pull request this week.

**Comment by mdhender** [comment]
FWIW, the JSON command converts the binary data to a structure like:
```json
{
  "turn": 41,
  "cluster": {
    "radius": 25,
    "d_num_species": 27,
    "systems": [
      {
        "id": 1,
        "coords": {
          "x": 1,
          "y": 22,
          "z": 31
        },
        "type": "main_sequence",
        "color": "blue",
        "size": 4,
        "home_system": true,
        "visited_by": [
          1,
          5,
          8,
          15
        ],
        "planets": [
          {
            "orbit": 1,
            "diameter": 8,
            "econ_efficiency": 100,
            "gravity": 42,
            "mining_difficulty": 36,
            "pressure_class": 0,
            "temperature_class": 28
          },
```

The JSON file can be edited by hand and then converted back to the binary data format used by the game engine.

**Comment by mdhender** [comment]
Fixed by https://github.com/Ramblurr/Far-Horizons/pull/7

**Comment by Ramblurr** [comment]
merged!
